export enum Size {
  LG = 'lg',
  MD = 'md',
  SM = 'sm'
}

export enum OWNER {
  SCENE_TREE = 'SCENE_TREE',
  ELEMENT_SELECTION = 'ELEMENT_SELECTION'
}

export enum UNDO {
  NONE = 'NONE',
  UNDO = 'UNDO',
  REDO = 'REDO'
}

export enum SCENE_TREE_ACTIONS {
  ADD_ELEMENT = 'ADD_ELEMENT',
  REMOVE_ELEMENT = 'REMOVE_ELEMENT',
  UPDATE_ELEMENT = 'UPDATE_ELEMENT'
}

export enum SELECTION_TYPES {
  ELEMENT = 'element',
  VERTEX = 'vertex'
}

export enum SELECTION_ACTIONS {
  SELECT_ELEMENTS = 'SELECT_ELEMENTS',
  DESELECT_ELEMENTS = 'DESELECT_ELEMENTS',
  SELECT_VERTICES = 'SELECT_VERTICES',
  DESELECT_VERTICES = 'DESELECT_VERTICES'
}
