export const DEFAULT_PRESET_ENGINE_ID = '@asyra/render-engine-pixi'

export const LEGACY_PRESET_ENGINE_FACTORY_ID =
  '@asyra/preset/legacy-render-engine-factory'

export const PRESET_COMPOSITION_ERROR_CODES = {
  INVALID_COMPOSITION: 'INVALID_COMPOSITION',
  DUPLICATE_TARGET: 'DUPLICATE_TARGET',
  UNKNOWN_ENGINE_BOOTSTRAP: 'UNKNOWN_ENGINE_BOOTSTRAP',
  MISSING_CAPABILITY_BUNDLE: 'MISSING_CAPABILITY_BUNDLE',
  ORDERING_CONFLICT: 'ORDERING_CONFLICT',
  LAYER_INSTALL_FAILED: 'LAYER_INSTALL_FAILED',
  CLEANUP_FAILED: 'CLEANUP_FAILED'
} as const

export type PresetCompositionErrorCode =
  (typeof PRESET_COMPOSITION_ERROR_CODES)[keyof typeof PRESET_COMPOSITION_ERROR_CODES]
