// Import features to register them via defineFeature()
import './switch-primary-tool'
import './create-element'
import './move-elements'
import './selection'
import './delete-element'
import './delete-vector-point'
import './hover-element'
import './zoom'
import './zoom-fit'
import './pan'
import './undo-redo'
import './group-elements'
import './layer-hierarchy-move'
import './pen-tool'
import './gradient-fill-handles'
