export const PresetProfiles = Object.freeze({
  '2D': '2D',
  '3D': '3D',
  HYBRID: 'HYBRID',
  CUSTOM: 'CUSTOM'
} as const)

export const PresetDefaults = Object.freeze({
  BASIC_SHAPES: 'basic-shapes',
  CONTAINERS: 'containers',
  VECTOR: 'vector',
  INPUT: 'input',
  SELECTION: 'selection',
  VECTOR_EDITING: 'vector-editing',
  VIEWPORT: 'viewport',
  UI_CONTEXT: 'ui-context'
} as const)

export const PRESET_APPLY_ERROR_CODES = Object.freeze({
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  UNKNOWN_PROFILE: 'UNKNOWN_PROFILE',
  UNAVAILABLE_PROFILE: 'UNAVAILABLE_PROFILE',
  UNKNOWN_DEFAULT: 'UNKNOWN_DEFAULT',
  UNAVAILABLE_DEFAULT: 'UNAVAILABLE_DEFAULT',
  DUPLICATE_DEFAULT: 'DUPLICATE_DEFAULT',
  COMPOSITION_CLOSED: 'COMPOSITION_CLOSED',
  ALREADY_APPLIED: 'ALREADY_APPLIED',
  ENGINE_PROVIDER_CONFLICT: 'ENGINE_PROVIDER_CONFLICT',
  DEFAULT_INSTALL_FAILED: 'DEFAULT_INSTALL_FAILED',
  CLEANUP_FAILED: 'CLEANUP_FAILED'
} as const)
