export enum SELECTION_TYPES {
  ELEMENT = 'element',
  VERTEX = 'vertex'
}

export enum SELECTION_ACTIONS {
  SELECT_ELEMENTS = 'SELECT_ELEMENTS',
  DESELECT_ELEMENTS = 'DESELECT_ELEMENTS',
  SELECT_VERTICES = 'SELECT_VERTICES',
  DESELECT_VERTICES = 'DESELECT_VERTICES'
}
