name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        run: corepack enable && yarn set version 4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Validate workspace dependencies
        run: yarn deps:validate

      - name: Validate turbo.json
        run: yarn gen:turbo:check

      - name: Build React
        run: yarn react:build

      - name: Lint
        run: yarn lint:ci

      - name: Test
        if: success()
        run: yarn test:ci

      - name: Validate generated app template
        run: yarn release:app:check --prod=asyra-design

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Yarn
        run: corepack enable && yarn set version 4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
